module.exports = {
    local:{
        username: "upmesh",
        password: "upmesh12345",
        database: "upmesh_dev",
        host: "localhost",
        dialect: "mysql",
        operatorsAliases: 0,
        logging: false,
        define: {
            charset: "utf8",
            collate: "utf8_general_ci",
            timestamps: true,
        },
    },
    development: {
        username: "upmesh",
        password: "upmesh12345",
        database: "upmesh_dev",
        host: "db",
        dialect: "mysql",
        operatorsAliases: 0,
        logging: false,
        define: {
            charset: "utf8",
            collate: "utf8_general_ci",
            timestamps: true,
        },
    },
    staging: {
        username: "upmesh",
        password: "upmesh12345",
        database: "upmesh_stage",
        host: "db",
        dialect: "mysql",
        operatorsAliases: 0,
        logging: false,
        define: {
            charset: "utf8",
            collate: "utf8_general_ci",
            timestamps: true,
        },
    },
    production: {
        username: "upmesh",
        password: "upmesh12345",
        database: "upmesh_prod",
        host: "db",
        dialect: "mysql",
        operatorsAliases: 0,
        logging: false,
        define: {
            charset: "utf8",
            collate: "utf8_general_ci",
            timestamps: true,
        },
    },
};
