name: Continues Integration
'on':
  push:
    branches:
      - develop
jobs:
  build-test:
    name: Build and Run Unit Test
    runs-on: ubuntu-latest
    services:
      mydb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host mydb  -uroot -ppassword -e "SHOW DATABASES"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: 'echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"'
        id: extract_branch
      - name: setup test database
        run: |
          npm install sequelize-cli
          NODE_ENV=test npx sequelize-cli db:create --env test 
          NODE_ENV=test npx sequelize-cli db:migrate --env test
      - name: Unit Testing
        run: |
          npm install jest
          npm test
