name: Develop-CD
'on':
  push:
    branches:
      - develop
jobs:
  build-test:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - name: Checkout
        uses: actions/checkout@v1
  upload-image:
    needs: built-test
    name: Upload Image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

