name: Develop-CI
'on':
  push:
    branches:
      - master
jobs:
  buildTest:
    name: Build and Run Unit Test
    runs-on: ubuntu-latest
    services:
      mydb:
        image: 'mysql:5.7'
        env:
          MYSQL_ROOT_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=4s
          --health-timeout=5s --health-retries=2
    steps:
      - name: Verify MySQL connection from container 
        run: |
          apt-get install -y mysql-client
          mysql --host mydb -uroot -ppassword -e "SHOW DATABASES"
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - name: Checkout
        uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: 'echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"'
        id: extract_branch
      - name: setup test database
        run: |
          npm install sequelize-cli
          NODE_ENV=test npx sequelize-cli db:create --env test 
          NODE_ENV=test npx sequelize-cli db:migrate --env test
      - name: Unit Testing
        run: |
          npm install jest
          npm test
