'on':
  push:
    branches:
      - develop-stage
      - develop
      - release/*
      - hotfix/*
      - feature/*
jobs:
  buildTest:
    name: Build and Run Unit Test
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mydb:
        image: 'mysql:5.7'
        env:
          MYSQL_ROOT_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=4s
          --health-timeout=5s --health-retries=2
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: 'echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"'
        id: extract_branch
      - name: .env generation
        run: node ./env/json_environments
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
